<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3registrationeb"
 *
 * Auto generated by Extension Builder 2013-04-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3 Registration',
	'description' => 'New T3Registration built in extbase',
	'category' => 'plugin',
	'author' => 'Federico Bernardin',
	'author_email' => 'federico@bernardin.it',
	'author_company' => 'BFConsulting',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>